export enum XIVPlayerJob {
  PLD = 'Paladin',
  WAR = 'Warrior',
  GNB = 'Gunbreaker',
  DRK = 'Dark Knight',
  WHM = 'White Mage',
  AST = 'Astrologian',
  SCH = 'Scholar',
  MNK = 'Monk',
  DRG = 'Dragoon',
  NIN = 'Ninja',
  SAM = 'Samurai',
  BRD = 'Bard',
  MCH = 'Machinist',
  DNC = 'Dancer',
  BLM = 'Black Mage',
}
